encryptionsalt: v1:511JMr/Tc2k=:v1:8s6EHv8iyjslYWcC:56BwQW719hd51g3WKknCs2L80gZ5DQ==
config:
  startup-factory-infra:coolifyApiKey:
    secure: v1:py3iBO8ZHY7Bb5uG:qUUq93Nk+GVT2sy8Ha3uYbCVxpIZC/fnUSZnxo9N9AaYlnBtSmffBltC0ebDUVCxkRiw8c8a2yGXIQ31MHQBgw==
